server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/user_service_db
    username: root
    password: root

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
